"""Shared AR/EN column labels for report exports (PDF/Excel) — one place so
the same term ("Debit", "Customer"...) isn't retranslated per report."""

from __future__ import annotations

_LABELS: dict[str, dict[str, str]] = {
    "ar": {
        "account": "الحساب",
        "account_code": "رقم الحساب",
        "debit": "مدين",
        "credit": "دائن",
        "balance": "الرصيد",
        "opening_balance": "الرصيد الافتتاحي",
        "closing_balance": "الرصيد الختامي",
        "date": "التاريخ",
        "reference": "المرجع",
        "status": "الحالة",
        "description": "البيان",
        "source": "المصدر",
        "customer": "العميل",
        "vendor": "المورد",
        "product": "الصنف",
        "warehouse": "المستودع",
        "qty": "الكمية",
        "unit_cost": "تكلفة الوحدة",
        "running_qty": "الرصيد الجاري",
        "running_balance": "الرصيد الجاري",
        "total": "الإجمالي",
        "amount": "المبلغ",
        "type": "النوع",
        "period": "الفترة",
        "invoice_count": "عدد الفواتير",
        "revenue": "الإيرادات",
        "days_overdue": "أيام التأخير",
        "bucket": "الفئة العمرية",
        "sales_subtotal": "صافي المبيعات",
        "output_vat": "ضريبة المخرجات (المبيعات)",
        "sales_total": "إجمالي المبيعات",
        "purchases_subtotal": "صافي المشتريات",
        "input_vat": "ضريبة المدخلات (المشتريات)",
        "purchases_total": "إجمالي المشتريات",
        "net_vat_payable": "صافي الضريبة المستحقة",
        "payments_received": "المدفوعات المحصّلة",
        "payments_made": "المدفوعات المسددة",
        "adjustments": "التسويات (إشعارات خصم)",
        "net_purchases": "صافي المشتريات بعد التسويات",
        "cost": "التكلفة",
        "accumulated_depreciation": "مجمع الإهلاك",
        "net_book_value": "صافي القيمة الدفترية",
        "asset_code": "رمز الأصل",
        "register_total": "إجمالي السجل",
        "gl_balance": "رصيد الأستاذ العام",
        "difference": "الفرق",
        "asset_name": "اسم الأصل",
        "category": "التصنيف",
        "useful_life_months": "العمر الإنتاجي (أشهر)",
        "cost_center": "مركز التكلفة",
        "net_result": "صافي الأثر",
        "asset": "أصول",
        "liability": "التزامات",
        "equity": "حقوق الملكية",
        "expense": "مصروفات",
        "number": "رقم المستند",
        "partner": "العميل / المورد",
        "vat_amount": "قيمة الضريبة",
    },
    "en": {
        "account": "Account",
        "account_code": "Account Code",
        "debit": "Debit",
        "credit": "Credit",
        "balance": "Balance",
        "opening_balance": "Opening Balance",
        "closing_balance": "Closing Balance",
        "date": "Date",
        "reference": "Reference",
        "status": "Status",
        "description": "Description",
        "source": "Source",
        "customer": "Customer",
        "vendor": "Vendor",
        "product": "Product",
        "warehouse": "Warehouse",
        "qty": "Qty",
        "unit_cost": "Unit Cost",
        "running_qty": "Running Qty",
        "running_balance": "Running Balance",
        "total": "Total",
        "amount": "Amount",
        "type": "Type",
        "period": "Period",
        "invoice_count": "Invoices",
        "revenue": "Revenue",
        "days_overdue": "Days Overdue",
        "bucket": "Aging Bucket",
        "sales_subtotal": "Net Sales",
        "output_vat": "Output VAT (Sales)",
        "sales_total": "Total Sales",
        "purchases_subtotal": "Net Purchases",
        "input_vat": "Input VAT (Purchases)",
        "purchases_total": "Total Purchases",
        "net_vat_payable": "Net VAT Payable",
        "payments_received": "Payments Received",
        "payments_made": "Payments Made",
        "adjustments": "Adjustments (Debit Notes)",
        "net_purchases": "Net Purchases",
        "cost": "Cost",
        "accumulated_depreciation": "Accumulated Depreciation",
        "net_book_value": "Net Book Value",
        "asset_code": "Asset Code",
        "register_total": "Register Total",
        "gl_balance": "GL Balance",
        "difference": "Difference",
        "asset_name": "Asset Name",
        "category": "Category",
        "useful_life_months": "Useful Life (months)",
        "cost_center": "Cost Center",
        "net_result": "Net Result",
        "asset": "Assets",
        "liability": "Liabilities",
        "equity": "Equity",
        "expense": "Expenses",
        "number": "Document No.",
        "partner": "Customer / Vendor",
        "vat_amount": "VAT Amount",
    },
}

_TITLES: dict[str, dict[str, str]] = {
    "ar": {
        "trial_balance": "ميزان المراجعة",
        "general_ledger": "دفتر الأستاذ العام",
        "income_statement": "قائمة الدخل",
        "balance_sheet": "الميزانية العمومية",
        "customer_subledger": "كشف حساب عميل",
        "vendor_subledger": "كشف حساب مورد",
        "ar_aging": "أعمار ذمم العملاء",
        "ap_aging": "أعمار ذمم الموردين",
        "sales_by_customer": "المبيعات حسب العميل",
        "sales_by_product": "المبيعات حسب الصنف",
        "sales_by_period": "المبيعات حسب الفترة",
        "purchases_by_supplier": "المشتريات حسب المورد",
        "product_cardex": "بطاقة الصنف القياسية",
        "vat_summary": "ملخص ضريبة القيمة المضافة",
        "vat_detail": "تقرير ضريبة القيمة المضافة التفصيلي",
        "inventory_valuation": "تقييم المخزون",
        "fixed_asset_card": "بطاقة الأصل الثابت",
        "fixed_assets_reconciliation": "تسوية الأصول الثابتة مع الأستاذ العام",
        "fixed_assets_register": "سجل الأصول الثابتة",
        "fixed_assets_depreciation_schedule": "جدول إهلاك الأصول الثابتة",
        "cost_center_report": "تقرير مركز التكلفة",
    },
    "en": {
        "trial_balance": "Trial Balance",
        "general_ledger": "General Ledger",
        "income_statement": "Income Statement",
        "balance_sheet": "Balance Sheet",
        "customer_subledger": "Customer Statement",
        "vendor_subledger": "Vendor Statement",
        "ar_aging": "Accounts Receivable Aging",
        "ap_aging": "Accounts Payable Aging",
        "sales_by_customer": "Sales by Customer",
        "sales_by_product": "Sales by Product",
        "sales_by_period": "Sales by Period",
        "purchases_by_supplier": "Purchases by Supplier",
        "product_cardex": "Standard Product Cardex",
        "vat_summary": "VAT Summary",
        "vat_detail": "VAT Detail Report",
        "inventory_valuation": "Inventory Valuation",
        "fixed_asset_card": "Fixed Asset Card",
        "fixed_assets_reconciliation": "Fixed Assets Reconciliation to GL",
        "fixed_assets_register": "Fixed Assets Register",
        "fixed_assets_depreciation_schedule": "Fixed Assets Depreciation Schedule",
        "cost_center_report": "Cost Center Report",
    },
}


def label(lang: str, key: str) -> str:
    return _LABELS.get(lang, _LABELS["ar"]).get(key, key)


def title(lang: str, report_key: str) -> str:
    return _TITLES.get(lang, _TITLES["ar"]).get(report_key, report_key)
