"""identity module M0 foundation

Revision ID: 42f822ff912d
Revises: 1da019d58514
Create Date: 2026-07-31 18:52:57.270844
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '42f822ff912d'
down_revision: Union[str, None] = '1da019d58514'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('full_name', sa.Text(), nullable=False),
    sa.Column('preferred_locale', sa.Text(), server_default='ar', nullable=False),
    sa.Column('preferred_calendar', sa.Text(), server_default='gregorian', nullable=False),
    sa.Column('totp_secret', sa.Text(), nullable=True),
    sa.Column('is_2fa_enabled', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("preferred_calendar IN ('gregorian','hijri')", name='ck_user_calendar'),
    sa.CheckConstraint("preferred_locale IN ('ar','en')", name='ck_user_locale'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_tenant_id'), 'app_user', ['tenant_id'], unique=False)
    op.create_index('ux_app_user_email_lower', 'app_user', [sa.literal_column('lower(email)')], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('currency',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.String(length=3), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('decimal_places', sa.SmallInteger(), server_default=sa.text('2'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('permission',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('scope', sa.Text(), nullable=False),
    sa.CheckConstraint("scope IN ('screen','field','action')", name='ck_permission_scope'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('tenant',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('legal_name', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activity_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.Text(), nullable=False),
    sa.Column('target_table', sa.Text(), nullable=True),
    sa.Column('target_id', sa.UUID(), nullable=True),
    sa.Column('occurred_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_activity_log_company_date', 'activity_log', ['company_id', 'occurred_at'], unique=False)
    op.create_index(op.f('ix_activity_log_company_id'), 'activity_log', ['company_id'], unique=False)
    op.create_index(op.f('ix_activity_log_tenant_id'), 'activity_log', ['tenant_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('target_table', sa.Text(), nullable=False),
    sa.Column('target_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.Text(), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_company_id'), 'audit_log', ['company_id'], unique=False)
    op.create_index('ix_audit_log_target', 'audit_log', ['target_table', 'target_id'], unique=False)
    op.create_index(op.f('ix_audit_log_tenant_id'), 'audit_log', ['tenant_id'], unique=False)
    op.create_table('company',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('legal_name', sa.Text(), nullable=False),
    sa.Column('legal_name_ar', sa.Text(), nullable=False),
    sa.Column('vat_number', sa.String(length=15), nullable=False),
    sa.Column('cr_number', sa.String(length=20), nullable=True),
    sa.Column('base_currency_id', sa.UUID(), nullable=False),
    sa.Column('valuation_method', sa.Text(), nullable=False),
    sa.Column('zatca_environment', sa.Text(), server_default='sandbox', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint("valuation_method IN ('fifo','average')", name='ck_company_valuation_method'),
    sa.CheckConstraint("zatca_environment IN ('sandbox','simulation','production')", name='ck_company_zatca_env'),
    sa.ForeignKeyConstraint(['base_currency_id'], ['currency.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_company_tenant_id'), 'company', ['tenant_id'], unique=False)
    op.create_index('ux_company_vat', 'company', ['vat_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('branch',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=False),
    sa.Column('is_main', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_branch_company_id'), 'branch', ['company_id'], unique=False)
    op.create_index(op.f('ix_branch_tenant_id'), 'branch', ['tenant_id'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_permission',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('user_company_access',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['branch_id'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['company_id'], ['company.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'company_id', 'branch_id', name='ux_user_company_branch')
    )
    op.create_table('user_role',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'role_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('user_company_access')
    op.drop_table('role_permission')
    op.drop_table('role')
    op.drop_index(op.f('ix_branch_tenant_id'), table_name='branch')
    op.drop_index(op.f('ix_branch_company_id'), table_name='branch')
    op.drop_table('branch')
    op.drop_index('ux_company_vat', table_name='company', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_company_tenant_id'), table_name='company')
    op.drop_table('company')
    op.drop_index(op.f('ix_audit_log_tenant_id'), table_name='audit_log')
    op.drop_index('ix_audit_log_target', table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_company_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_activity_log_tenant_id'), table_name='activity_log')
    op.drop_index(op.f('ix_activity_log_company_id'), table_name='activity_log')
    op.drop_index('ix_activity_log_company_date', table_name='activity_log')
    op.drop_table('activity_log')
    op.drop_table('tenant')
    op.drop_table('permission')
    op.drop_table('currency')
    op.drop_index('ux_app_user_email_lower', table_name='app_user', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_app_user_tenant_id'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
