"""inventory module M3

Revision ID: 5795e21946f2
Revises: f81e8530ddbd
Create Date: 2026-07-31 20:20:58.904175
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5795e21946f2'
down_revision: Union[str, None] = 'f81e8530ddbd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('warehouse',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_warehouse_company_id'), 'warehouse', ['company_id'], unique=False)
    op.create_table('cycle_count',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.CheckConstraint("status IN ('draft','counted','approved')", name='ck_cycle_count_status'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cycle_count_company_id'), 'cycle_count', ['company_id'], unique=False)
    op.create_table('location',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('is_virtual', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouse.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('stock_layer',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('qty_remaining', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('qty_remaining >= 0', name='ck_stock_layer_nonnegative'),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_layer_company_id'), 'stock_layer', ['company_id'], unique=False)
    op.create_index('ix_stock_layer_fifo', 'stock_layer', ['product_id', 'location_id', 'received_at'], unique=False)
    op.create_table('stock_move',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('source_location_id', sa.UUID(), nullable=True),
    sa.Column('dest_location_id', sa.UUID(), nullable=True),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('move_type', sa.Text(), nullable=False),
    sa.Column('source_table', sa.Text(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('moved_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.CheckConstraint("move_type IN ('receipt', 'delivery', 'transfer', 'adjustment')", name='ck_stock_move_type'),
    sa.CheckConstraint('qty > 0', name='ck_stock_move_qty_positive'),
    sa.ForeignKeyConstraint(['dest_location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['source_location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_move_company_id'), 'stock_move', ['company_id'], unique=False)
    op.create_index('ix_stock_move_product_dest', 'stock_move', ['product_id', 'dest_location_id'], unique=False)
    op.create_index(op.f('ix_stock_move_product_id'), 'stock_move', ['product_id'], unique=False)
    op.create_table('stock_quant',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('qty_on_hand', sa.Numeric(precision=18, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('moving_avg_cost', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('product_id', 'location_id', name='ux_stock_quant_product_location')
    )
    op.create_index(op.f('ix_stock_quant_company_id'), 'stock_quant', ['company_id'], unique=False)
    op.create_table('cycle_count_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('cycle_count_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=False),
    sa.Column('system_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('counted_qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stock_move_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['cycle_count_id'], ['cycle_count.id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.ForeignKeyConstraint(['stock_move_id'], ['stock_move.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cycle_count_line')
    op.drop_index(op.f('ix_stock_quant_company_id'), table_name='stock_quant')
    op.drop_table('stock_quant')
    op.drop_index(op.f('ix_stock_move_product_id'), table_name='stock_move')
    op.drop_index('ix_stock_move_product_dest', table_name='stock_move')
    op.drop_index(op.f('ix_stock_move_company_id'), table_name='stock_move')
    op.drop_table('stock_move')
    op.drop_index('ix_stock_layer_fifo', table_name='stock_layer')
    op.drop_index(op.f('ix_stock_layer_company_id'), table_name='stock_layer')
    op.drop_table('stock_layer')
    op.drop_table('location')
    op.drop_index(op.f('ix_cycle_count_company_id'), table_name='cycle_count')
    op.drop_table('cycle_count')
    op.drop_index(op.f('ix_warehouse_company_id'), table_name='warehouse')
    op.drop_table('warehouse')
    # ### end Alembic commands ###
