"""partner product and sales module M2

Revision ID: 85e635298389
Revises: 461205cf56a6
Create Date: 2026-07-31 19:35:58.574114
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '85e635298389'
down_revision: Union[str, None] = '461205cf56a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('is_customer', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_vendor', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('vat_number', sa.Text(), nullable=True),
    sa.Column('cr_number', sa.Text(), nullable=True),
    sa.Column('address', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_partner_company', 'partner', ['company_id'], unique=False)
    op.create_index(op.f('ix_partner_company_id'), 'partner', ['company_id'], unique=False)
    op.create_index(op.f('ix_partner_tenant_id'), 'partner', ['tenant_id'], unique=False)
    op.create_index('ux_partner_vat', 'partner', ['company_id', 'vat_number'], unique=True, postgresql_where=sa.text('deleted_at IS NULL AND vat_number IS NOT NULL'))
    op.create_table('product_category',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['product_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_category_company_id'), 'product_category', ['company_id'], unique=False)
    op.create_table('quotation',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('currency_code', sa.Text(), server_default='SAR', nullable=False),
    sa.Column('quote_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'done', 'cancelled')", name='ck_quotation_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='ux_quotation_number')
    )
    op.create_index(op.f('ix_quotation_company_id'), 'quotation', ['company_id'], unique=False)
    op.create_table('product',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('sku', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('category_id', sa.UUID(), nullable=True),
    sa.Column('is_stockable', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('sales_price', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('cost_price', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('default_tax_rate_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_product_company_id'), 'product', ['company_id'], unique=False)
    op.create_index(op.f('ix_product_tenant_id'), 'product', ['tenant_id'], unique=False)
    op.create_index('ux_product_sku', 'product', ['company_id', 'sku'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('quotation_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_order',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('quotation_id', sa.UUID(), nullable=True),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('currency_code', sa.Text(), server_default='SAR', nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'done', 'cancelled')", name='ck_sales_order_status'),
    sa.ForeignKeyConstraint(['quotation_id'], ['quotation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='ux_sales_order_number')
    )
    op.create_index(op.f('ix_sales_order_company_id'), 'sales_order', ['company_id'], unique=False)
    op.create_table('sales_invoice',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=True),
    sa.Column('original_invoice_id', sa.UUID(), nullable=True),
    sa.Column('invoice_type', sa.Text(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('currency_code', sa.Text(), server_default='SAR', nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('version', sa.Integer(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("invoice_type IN ('tax', 'simplified', 'credit_note', 'debit_note')", name='ck_sales_invoice_type'),
    sa.CheckConstraint("status IN ('draft', 'pending_submission', 'cleared', 'reported', 'rejected', 'cancelled')", name='ck_sales_invoice_status'),
    sa.ForeignKeyConstraint(['original_invoice_id'], ['sales_invoice.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='ux_sales_invoice_number')
    )
    op.create_index(op.f('ix_sales_invoice_company_id'), 'sales_invoice', ['company_id'], unique=False)
    op.create_table('sales_order_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sales_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate_id', sa.UUID(), nullable=False),
    sa.Column('qty_invoiced', sa.Numeric(precision=18, scale=6), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales_invoice_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sales_invoice_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate_id', sa.UUID(), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zatca_submission',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('sales_invoice_id', sa.UUID(), nullable=False),
    sa.Column('uuid_value', sa.UUID(), nullable=False),
    sa.Column('icv', sa.Integer(), nullable=False),
    sa.Column('previous_hash', sa.Text(), nullable=False),
    sa.Column('invoice_hash', sa.Text(), nullable=False),
    sa.Column('qr_payload', sa.Text(), nullable=False),
    sa.Column('xml_document', sa.Text(), nullable=False),
    sa.Column('submission_mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending_submission', nullable=False),
    sa.Column('zatca_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('retry_count', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'pending_submission', 'cleared', 'reported', 'rejected', 'cancelled')", name='ck_zatca_submission_status'),
    sa.CheckConstraint("submission_mode IN ('clearance','reporting')", name='ck_zatca_submission_mode'),
    sa.ForeignKeyConstraint(['sales_invoice_id'], ['sales_invoice.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ux_zatca_invoice', 'zatca_submission', ['sales_invoice_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ux_zatca_invoice', table_name='zatca_submission')
    op.drop_table('zatca_submission')
    op.drop_table('sales_invoice_line')
    op.drop_table('sales_order_line')
    op.drop_index(op.f('ix_sales_invoice_company_id'), table_name='sales_invoice')
    op.drop_table('sales_invoice')
    op.drop_index(op.f('ix_sales_order_company_id'), table_name='sales_order')
    op.drop_table('sales_order')
    op.drop_table('quotation_line')
    op.drop_index('ux_product_sku', table_name='product', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_product_tenant_id'), table_name='product')
    op.drop_index(op.f('ix_product_company_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_quotation_company_id'), table_name='quotation')
    op.drop_table('quotation')
    op.drop_index(op.f('ix_product_category_company_id'), table_name='product_category')
    op.drop_table('product_category')
    op.drop_index('ux_partner_vat', table_name='partner', postgresql_where=sa.text('deleted_at IS NULL AND vat_number IS NOT NULL'))
    op.drop_index(op.f('ix_partner_tenant_id'), table_name='partner')
    op.drop_index(op.f('ix_partner_company_id'), table_name='partner')
    op.drop_index('ix_partner_company', table_name='partner')
    op.drop_table('partner')
    # ### end Alembic commands ###
