"""accounting module M1

Revision ID: e5a4af408356
Revises: 42bc09c34924
Create Date: 2026-07-31 19:13:05.822608
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e5a4af408356'
down_revision: Union[str, None] = '42bc09c34924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account_type',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.CheckConstraint("code IN ('asset','liability','equity','revenue','expense')", name='ck_account_type_code'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('cost_center',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_center_company_id'), 'cost_center', ['company_id'], unique=False)
    op.create_table('fiscal_period',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'period_start', 'period_end', name='ux_fiscal_period')
    )
    op.create_index(op.f('ix_fiscal_period_company_id'), 'fiscal_period', ['company_id'], unique=False)
    op.create_table('tax_group',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_group_company_id'), 'tax_group', ['company_id'], unique=False)
    op.create_table('account',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('name_ar', sa.Text(), nullable=True),
    sa.Column('account_type_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['account_type_id'], ['account_type.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_account_company_id'), 'account', ['company_id'], unique=False)
    op.create_index('ux_account_code', 'account', ['company_id', 'code'], unique=True, postgresql_where=sa.text('deleted_at IS NULL'))
    op.create_table('tax_rate',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('tax_group_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('rate_percent', sa.Numeric(precision=5, scale=2), server_default=sa.text('0'), nullable=False),
    sa.Column('is_withholding', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.CheckConstraint("kind IN ('standard','zero_rated','exempt','out_of_scope')", name='ck_tax_rate_kind'),
    sa.ForeignKeyConstraint(['tax_group_id'], ['tax_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tax_rate_company_id'), 'tax_rate', ['company_id'], unique=False)
    op.create_table('journal',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('default_debit_account_id', sa.UUID(), nullable=True),
    sa.Column('default_credit_account_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['default_credit_account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['default_debit_account_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'code', name='ux_journal_code')
    )
    op.create_index(op.f('ix_journal_company_id'), 'journal', ['company_id'], unique=False)
    op.create_table('journal_entry',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=True),
    sa.Column('journal_id', sa.UUID(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('reference', sa.Text(), nullable=True),
    sa.Column('source_table', sa.Text(), nullable=True),
    sa.Column('source_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('reversed_entry_id', sa.UUID(), nullable=True),
    sa.Column('posted_at', sa.DateTime(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('version', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.CheckConstraint("status IN ('draft','posted','reversed')", name='ck_journal_entry_status'),
    sa.ForeignKeyConstraint(['journal_id'], ['journal.id'], ),
    sa.ForeignKeyConstraint(['reversed_entry_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_company_id'), 'journal_entry', ['company_id'], unique=False)
    op.create_index('ix_journal_entry_source', 'journal_entry', ['source_table', 'source_id'], unique=False)
    op.create_table('journal_entry_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=False),
    sa.Column('account_id', sa.UUID(), nullable=False),
    sa.Column('cost_center_id', sa.UUID(), nullable=True),
    sa.Column('debit', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('credit', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.CheckConstraint('NOT (debit > 0 AND credit > 0)', name='ck_jel_debit_xor_credit'),
    sa.CheckConstraint('debit >= 0 AND credit >= 0', name='ck_jel_nonnegative'),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['cost_center_id'], ['cost_center.id'], ),
    sa.ForeignKeyConstraint(['journal_entry_id'], ['journal_entry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entry_line_account_id'), 'journal_entry_line', ['account_id'], unique=False)
    op.create_index(op.f('ix_journal_entry_line_journal_entry_id'), 'journal_entry_line', ['journal_entry_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_journal_entry_line_journal_entry_id'), table_name='journal_entry_line')
    op.drop_index(op.f('ix_journal_entry_line_account_id'), table_name='journal_entry_line')
    op.drop_table('journal_entry_line')
    op.drop_index('ix_journal_entry_source', table_name='journal_entry')
    op.drop_index(op.f('ix_journal_entry_company_id'), table_name='journal_entry')
    op.drop_table('journal_entry')
    op.drop_index(op.f('ix_journal_company_id'), table_name='journal')
    op.drop_table('journal')
    op.drop_index(op.f('ix_tax_rate_company_id'), table_name='tax_rate')
    op.drop_table('tax_rate')
    op.drop_index('ux_account_code', table_name='account', postgresql_where=sa.text('deleted_at IS NULL'))
    op.drop_index(op.f('ix_account_company_id'), table_name='account')
    op.drop_table('account')
    op.drop_index(op.f('ix_tax_group_company_id'), table_name='tax_group')
    op.drop_table('tax_group')
    op.drop_index(op.f('ix_fiscal_period_company_id'), table_name='fiscal_period')
    op.drop_table('fiscal_period')
    op.drop_index(op.f('ix_cost_center_company_id'), table_name='cost_center')
    op.drop_table('cost_center')
    op.drop_table('account_type')
    # ### end Alembic commands ###
