"""purchasing module M4

Revision ID: fc93d906d5ba
Revises: c7d1f40b5718
Create Date: 2026-07-31 20:47:52.142080
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'fc93d906d5ba'
down_revision: Union[str, None] = 'c7d1f40b5718'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_order',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('currency_code', sa.Text(), server_default='SAR', nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'done', 'cancelled')", name='ck_purchase_order_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='ux_purchase_order_number')
    )
    op.create_index(op.f('ix_purchase_order_company_id'), 'purchase_order', ['company_id'], unique=False)
    op.create_table('goods_receipt',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('warehouse_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('receipt_date', sa.Date(), nullable=False),
    sa.CheckConstraint("status IN ('draft', 'confirmed', 'done', 'cancelled')", name='ck_goods_receipt_status'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goods_receipt_company_id'), 'goods_receipt', ['company_id'], unique=False)
    op.create_table('purchase_order_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate_id', sa.UUID(), nullable=False),
    sa.Column('qty_received', sa.Numeric(precision=18, scale=6), server_default=sa.text('0'), nullable=False),
    sa.Column('qty_billed', sa.Numeric(precision=18, scale=6), server_default=sa.text('0'), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_bill',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('branch_id', sa.UUID(), nullable=False),
    sa.Column('partner_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_id', sa.UUID(), nullable=False),
    sa.Column('number', sa.Text(), nullable=False),
    sa.Column('vendor_reference', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='draft', nullable=False),
    sa.Column('currency_code', sa.Text(), server_default='SAR', nullable=False),
    sa.Column('bill_date', sa.Date(), nullable=False),
    sa.Column('subtotal_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=18, scale=4), server_default=sa.text('0'), nullable=False),
    sa.Column('journal_entry_id', sa.UUID(), nullable=True),
    sa.Column('mismatch_reasons', sa.Text(), nullable=True),
    sa.CheckConstraint("status IN ('draft', 'matched', 'mismatched', 'approved', 'posted')", name='ck_vendor_bill_status'),
    sa.ForeignKeyConstraint(['purchase_order_id'], ['purchase_order.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'number', name='ux_vendor_bill_number')
    )
    op.create_index(op.f('ix_vendor_bill_company_id'), 'vendor_bill', ['company_id'], unique=False)
    op.create_table('goods_receipt_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('goods_receipt_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('stock_move_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['goods_receipt_id'], ['goods_receipt.id'], ),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_line.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vendor_bill_line',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('vendor_bill_id', sa.UUID(), nullable=False),
    sa.Column('purchase_order_line_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('qty', sa.Numeric(precision=18, scale=6), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_rate_id', sa.UUID(), nullable=False),
    sa.Column('tax_rate_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=18, scale=4), nullable=False),
    sa.ForeignKeyConstraint(['purchase_order_line_id'], ['purchase_order_line.id'], ),
    sa.ForeignKeyConstraint(['vendor_bill_id'], ['vendor_bill.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vendor_bill_line')
    op.drop_table('goods_receipt_line')
    op.drop_index(op.f('ix_vendor_bill_company_id'), table_name='vendor_bill')
    op.drop_table('vendor_bill')
    op.drop_table('purchase_order_line')
    op.drop_index(op.f('ix_goods_receipt_company_id'), table_name='goods_receipt')
    op.drop_table('goods_receipt')
    op.drop_index(op.f('ix_purchase_order_company_id'), table_name='purchase_order')
    op.drop_table('purchase_order')
    # ### end Alembic commands ###
